name: Code Quality

# This defines the triggers for the workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check:

    # This defines the type of machine to run the job on
    runs-on: ubuntu-latest

    steps:

    # This step copies your repository code to the runner
    - uses: actions/checkout@v4

    # This step sets up Python on the runner
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    # This step installs uv
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7

    # The next steps use *run* to execute commands on the runner
    # This is just like typing commands in the Codespace terminal

    # This step installs dependencies
    - name: Install dependencies
      run: |
        uv sync

    # This step runs unit tests with pytest
    # (we need -m so that our tests can find our notebook code)
    - name: Test with pytest
      run: |
        uv run -m pytest

    # These steps run checks against the codebase
    - name: Lint with ruff
      run: |
        uvx ruff check

    - name: Format with ruff
      run: |
        uvx ruff format

    - name: Type check with ty
      run: |
        uvx ty check

    - name: Format imports with isort
      run: |
        uvx isort .